#邮件服务器地址
#spring.mail.host=smtp.sina.com
#spring.mail.username=gxlbt
#spring.mail.password=9ef44486f95c5211
#spring.mail.default-encoding=UTF-8
#spring.mail.protocol=smtp
#spring.mail.emailSender =gxlbt@sina.com

spring:
  mail:
    host: smtp.sina.com # 发件服务器
    username: gxlbt@sina.com # 账号
    password: 9ef44486f95c5211 # 密码（163需要授权第三方登录密码，请查看设置-客户端授权码密码开通）
    port: 465
    protocol: smtp
    default-encoding: utf-8
    # 下面这些配置大家不用深究，主要用于配置ssl
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
          starttls:
            enable: true
            required: true
      test-connection: false

# 邮件配置
lbt:
  email:
    subject: "系统通知"
    from: "gxlbt@sina.com"
    to: "javalbt@163.com"
    # 抄送人：类型定义为数组，可以配置多个
    cc:
      - "javalbt@163.com"

